services:

  proxy:
    image: nginx:latest
    ports:
      - "80:80" # map internal port 80 to external port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # use custom nginx config
    networks:
      - stubs_network

  stub1:
    build: .
    image: stub_image
    container_name: stub1
    ports:
      - "1234:1234"
    networks:
      - stubs_network
    hostname: stub1

  stub2:
    image: stub_image
    container_name: stub2
    depends_on:
      - stub1
    pull_policy: never
    ports:
      - "1235:1234"
    networks:
      - stubs_network
    hostname: stub2

  stub3:
    image: stub_image
    container_name: stub3
    depends_on:
      - stub2
    pull_policy: never
    ports:
      - "1236:1234"
    networks:
      - stubs_network
    hostname: stub3


networks:
  stubs_network:
    driver: bridge
